# Generated by Django 4.0.4 on 2022-05-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('rutCliente', models.IntegerField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut cliente')),
                ('nombreCliente', models.CharField(max_length=20, verbose_name='Nombre Cliente')),
                ('direccionCliente', models.CharField(max_length=20, verbose_name='Direccion Cliente')),
                ('numeroCliente', models.IntegerField(max_length=9, verbose_name='Numero Cliente')),
                ('emailCliente', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Cliente')),
                ('fechanacimientoCliente', models.DateField(verbose_name='Fecha Nacimiento Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigoProducto', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo Producto')),
                ('nombreProducto', models.CharField(max_length=20, verbose_name='Nombre Producto')),
                ('categoriaProducto', models.CharField(max_length=15, verbose_name='Categoria')),
                ('precioProducto', models.IntegerField(max_length=7, verbose_name='Precio Producto')),
            ],
        ),
    ]
