# Generated by Django 4.0.4 on 2022-05-23 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_producto_imagenproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombreCategoria', models.CharField(max_length=20, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoriaProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria'),
        ),
    ]
