# Generated by Django 4.0.4 on 2022-05-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cliente_numerocliente_alter_cliente_rutcliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigoProducto',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo Producto'),
        ),
    ]
