# Generated by Django 4.0.4 on 2022-07-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_producto_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stockProducto',
            field=models.IntegerField(default=0, verbose_name='Stock Producto'),
        ),
    ]
