# Generated by Django 4.0.4 on 2022-07-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customer_remove_carrito_cantidadcarrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
